FROM adoptopenjdk:15.0.2_7-jre-hotspot-focal

# Set working directory.
WORKDIR /app

# Add app.
COPY target/smappee-local-mqtt*.jar /appsmappee-local-mqtt.jar

RUN sed -i.bak \
    -e "s/securerandom.source=file:\/dev\/random/securerandom.source=file:\/dev\/urandom/g" \
    -e "s/securerandom.strongAlgorithms=NativePRNGBlocking/securerandom.strongAlgorithms=NativePRNG/g" \
    $JAVA_HOME/conf/security/java.security

CMD ["/opt/java/openjdk/bin/java", "-jar", "/app/smappee-local-mqtt.jar"]
